[package]
name = "contract-deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] } 
ethers = { version = "2.0", features = ["rustls"] }
eyre = "0.6"
hex = "0.4.3"
chrono = "0.4.38"
futures = "0.3.31" 
csv = "1.3.0"
